services:
  - type: web
    name: django-quick-start
    env: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    autoDeploy: false
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: django-quick-start
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ADMIN_URL
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
    - type: web
      name: flower
      region: ohio
      plan: free
      env: python
      buildCommand: "pip install -r requirements.txt"
      startCommand: "celery flower --app tasks --loglevel info"
      autoDeploy: false
      envVars:
        - key: CELERY_BROKER_URL
          fromService:
            type: redis
            name: celery-redis
            property: connectionString
    - type: redis
      name: celery-redis
      region: ohio
      plan: free # we choose a plan with persistence to ensure tasks are not lost upon restart
      maxmemoryPolicy: noeviction # recommended policy for queues
      ipAllowList: [] # only allow internal connections
