# Generated by Django 4.0.6 on 2022-07-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_test_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.subjects'),
        ),
    ]
