# Generated by Django 4.0.6 on 2022-07-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='subjects',
        ),
        migrations.AddField(
            model_name='questions',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.subjects'),
        ),
    ]
