# Generated by Django 4.0.6 on 2022-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_questions_subjects_questions_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='tests.questions'),
        ),
    ]
