# Generated by Django 4.0.6 on 2022-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_test_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, default=None, to='tests.questions'),
        ),
    ]
