# Generated by Django 4.0.6 on 2022-07-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_test_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Subjects',
            new_name='subjects',
        ),
    ]
