# Generated by Django 4.0.6 on 2022-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_testscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='answer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
