# Generated by Django 4.0.6 on 2022-07-27 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_subjects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscore',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
