# Generated by Django 4.0.6 on 2022-07-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_testscore_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.ManyToManyField(to='tests.answers'),
        ),
    ]
