# Generated by Django 4.0.6 on 2022-07-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_answers_remove_questions_answer_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='choices',
            field=models.ManyToManyField(related_name='question_choices', to='tests.answers'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='tests.answers'),
        ),
    ]
