# Generated by Django 4.0.6 on 2022-07-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_questions_choices_remove_questions_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_answer', to='tests.answers'),
        ),
    ]
