# Generated by Django 4.0.6 on 2022-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_alter_testquestions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
